version: '3.9'

services:
    backend:
      build:
        context: .
        dockerfile: ./server/Dockerfile
      container_name: node_container
      ports:
        - 4000:4000
      volumes:
        - ./server:/app/server
      depends_on:
        - postgres
        - redis
    frontend:
      build:
        context: .
        dockerfile: ./web/Dockerfile
      container_name: react_container
      tty: true
      volumes:
        - ./web:/app/client
      command: sh -c "cd /app/client && npm run dev"
      ports:
        - 3000:3000
    postgres:
      image: postgres:14
      container_name: postgres
      ports: 
        - 5432:5432
      volumes:
      - ./db-store:/var/lib/postgresql/data
      environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=lireddit12
    redis:
      image: redis:latest
      ports: 
        - 6379:6379